bases: []

environments:
  default: {}

repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: ealenn
  url: https://ealenn.github.io/charts

helmDefaults: {}

releases:
  - name: echo-server-helmfile
    namespace: test
    chart: ealenn/echo-server
    version: 0.3.1

missingFileHandler: Error
