bases: []

environments:
  default: {}

repositories:
- name: ealenn
  url: https://ealenn.github.io/charts

helmDefaults: {}

releases:
  - name: echo-server-helmfile
    namespace: test
    chart: ealenn/echo-server
    version: 0.5.0
    values: 
    - ingress:
        enabled: true
        hosts:
        - host: "localhost"
          paths: 
          - "/helmfile-echo"

missingFileHandler: Error
